version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.5
    working_directory: /go/schelper
    steps:
      - checkout
      - run: pwd && ls
      - run: go build -ldflags "-X github.com/mdsauce/schelper/cmd.CurVersion=`git rev-parse HEAD`"
      - run: go test ./...
      - run: ./schelper --version
      - run: ./schelper --help